---
title: "map_corals"
author: "ross"
date: "12/4/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(parzer)
library(tidyverse)
library(lubridate)
```

```{r}
# Read in coral collection info
md <- read_csv("collection_metadata.csv") %>%
  unite(date_time, date_sampled, time_sampled, sep = " ") %>%
  mutate(date_time = ymd_hms(date_time, tz = "Pacific/Tahiti"),
         date_time_min = format(date_time, "%F %H:%M"))

# md <- md %>%
#   separate(position, into = c("lat", "lon"), sep = "' ") %>%
#   mutate(lat = parse_lat(lat), lon = parse_lon(lon))
# 
# write_csv(md, "colony_metadata_parsed.csv")
```

```{r}
# Read in GPS tracks
gps_track_files <- list.files("data/gps_tracks", full.names = TRUE)

gps_tracks <- map_dfr(gps_track_files, read_csv, skip = 42, .id = "file_id") %>%
  janitor::clean_names() %>%
  mutate(file_id = basename(gps_track_files[as.numeric(file_id)])) %>%
  separate(file_id, into = c("gps_id", "date"), sep = "_")

gps_tracks <- gps_tracks %>%
  select(gps_id, time, lat, lon) %>%
  mutate(date_time = as_datetime(time, tz = "Pacific/Tahiti"),
         date_time_min = format(date_time, "%F %H:%M"))

# Get last lat/lon recorded for each discrete minute
gps_tracks <- gps_tracks %>%
  group_by(gps_id, date_time_min) %>%
  summarise(across(everything(), last))
```

```{r}
# Pull coral lat/lon from gps tracks based on date/time sampled
df <- left_join(md, gps_tracks, by = c("gps_id", "date_time_min"))

names(md)
names(gps_tracks)
```

